created Alex mode calculator without exceptions
jegius/java-education-base pull request #10
Opened 2019-08-10 08:29 UTC by AlexBossss

2019-08-10 08:48 UTC, jegius requested changes
нужно исправить замечания

2019-08-10 08:48 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +        try {
1) Блок try - catch повторяется в каждом методе, попробуй сделать отдельный метод который бы оборачивал операцию возбуждающую ошибку  в try-catch и обрабатывал бы ее. 
2) Попробуй вынести чтение одного и двух чисел с клавиатуры в отдельный метод, который бы принимал сообщение и вызывал сканер чтобы не использовать объект сканнер каждый раз в каждом методе.

2019-08-10 08:48 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +            System.out.println("Please enter only numbers!");
что будет если первое число будет верным а второе нет?

2019-08-10 08:48 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +            System.out.println("Enter number 1: ");
6 - 8 и 8 - 6 - это одно  и тоже? как я должен понять что именно из первого числа будет вычитаться второе? назови по понятнее.  То что ты выводишь конечному пользователю должно быть абсолютно однозначным.

2019-08-10 08:48 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +            System.out.println("Enter the number 1: ");
тоже самое 8 / 2 и 2 / 8 - разве одно и тоже? Избавься от неоднозначных number 1 и number 2 во всех операциях где расстановка операндов имеет значение

2019-08-10 08:48 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +    private long getFactorial(long value) {
еще одни момент по расположению методов. Сначала публичные \ протектед, потом приватные, у тебя сейчас все в перемешку

2019-08-10 08:48 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +            System.out.println(number + " in " + degree + "degree" + " = " + result);
кажется тут не хватает пробела

2019-08-21 06:32 UTC, Ravenous888 commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +        } catch (Exception exception) {
Нужны еще эксепшены!

2019-08-23 08:42 UTC, Ravenous888 commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +            } catch (NumberFormatException exeption) {
exception вместо exertion

2019-08-23 11:16 UTC, Ravenous888 commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
>              System.out.println("Please enter only numbers!");
Если буквы ввести, то сообщение не появляется.

2019-09-05 13:22 UTC, MaxKatyshev requested changes
вроде все ок

2019-09-17 06:34 UTC, jegius requested changes

2019-09-17 06:34 UTC, jegius commented on src/App.java
> +
лишние строки нужно удалить

2019-09-17 06:34 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +                Numbers.add(getString(scanner, optionalParameter));
в чем разница между optionalParameter и просто Parameter? в чем нобходимость использования этого?

2019-09-17 06:34 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +            System.out.println(messages[index]);
Почему не вывести сообщения с помощью forEach?

2019-09-17 06:34 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +            String[] messages,
У метода неоправданно много аргументов, нужно навести в них порядок, с ходу видно что от некоторых можно избавиться

2019-09-17 06:34 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +            if (parameter.equals(POSITIVE_NUMBER)) {
То же замечание что и максу, попробуй разделить валидацию и обработку ошибок. Вынеси все проверки в отдельный метод который кидает ошибки и выведи его тут.

2019-09-17 06:34 UTC, jegius commented on src/menu/commands/tasks/calculatormode/alex/Calculator.java
> +        String[] sqrtMessage = {"insert first number", "insert second number"};
1) у всех методов название sqrtMessage - нейминг странный;
2) у многих сообщения повторяются (sum, subtraction, multiply) нужно придумать способ как от этого можно избавиться.

2019-09-18 19:04 UTC, closed without merging