Max objects
jegius/java-education-base pull request #11
Opened 2019-08-23 21:09 UTC by Ravenous888

На проверку Лёшке

2019-09-01 16:08 UTC, jegius requested changes

2019-09-01 16:08 UTC, jegius commented on src/menu/commands/tasks/calculatormode/max/Calculator.java
> +        ArrayList <String> Numbers = new ArrayList<>(); {
в ссылке сделай List а не ArrayList, убери пробел между <String>и List

2019-09-01 16:08 UTC, jegius commented on src/menu/commands/tasks/calculatormode/max/Calculator.java
> +            for (int i = 0; i < messages.length; i++) {
здесь напрашивается foreach

2019-09-01 16:08 UTC, jegius commented on src/menu/commands/tasks/calculatormode/max/Calculator.java
> +
Убери лишние пробелы, между методами должно быть не более одной пустой строки

2019-09-01 16:08 UTC, jegius commented on src/menu/commands/tasks/calculatormode/max/Calculator.java
> +
После ретурна не должно быть пустой строки, к методам выше тоже относится

2019-09-01 16:08 UTC, jegius commented on src/menu/commands/tasks/calculatormode/max/Calculator.java
> +            if(parameter.equals(POSITIVE_NUMBER)) {
попробуй развить обработку ошибок и валидацию на два разных метода. ч

2019-09-24 18:06 UTC, MaxKatyshev commented on src/menu/commands/tasks/calculatormode/max/Calculator.java
> +            if(parameter.equals(POSITIVE_NUMBER)) {
готово

2019-09-25 11:00 UTC, jegius approved these changes

2019-09-25 11:00 UTC, jegius commented on src/menu/commands/littletasks/nurserycatsmax/CatShelterSingleton.java
> +//        houseOfCats.clear();
Это что? если не используется- удали

2019-09-25 11:00 UTC, jegius commented on src/menu/commands/littletasks/nurserycatsmax/MaxFamilies.java
> +            new Depps(),
до 10 семей нужно

2019-09-25 18:03 UTC, jegius approved these changes

2019-09-25 18:03 UTC, merged