Mini tasks
jegius/java-education-base pull request #12
Opened 2019-08-31 16:34 UTC by AlexBossss

2019-09-03 14:25 UTC, MaxKatyshev requested changes

2019-09-03 14:25 UTC, MaxKatyshev commented on src/menu/commands/littletasks/alexnurseryforcats/AlexNurseryForCats.java
> +    };
Надо до 10 семей

2019-09-03 14:25 UTC, MaxKatyshev commented on src/menu/commands/littletasks/alexnurseryforcats/families/Family.java
> +
Убрать пробелы (см. ниже)

2019-09-03 14:25 UTC, MaxKatyshev commented on src/menu/commands/littletasks/alexnurseryforcats/families/Nicksons.java
> +//        System.out.println(cats);
Это зло. Удаляй, пидр

2019-09-03 14:33 UTC, MaxKatyshev requested changes

2019-09-03 14:33 UTC, MaxKatyshev commented on src/menu/commands/littletasks/LittleTaskCommand.java
> +                AlexNinetyNineBottles.run();
Тут NinetyNineBottles зачем удалил? AlexNinetyNineBottles у тебя уже ниже есть

2019-09-17 10:50 UTC, MaxKatyshev reviewed
Не увидел ошибок. Вроде, все четко

2019-09-17 11:15 UTC, jegius requested changes

2019-09-17 11:15 UTC, jegius commented on src/menu/commands/littletasks/alexnurseryforcats/readme.md
> +## Приют для котов
readme мне кажется тут не к чему, достаточно readme в корне. Удали этот файл

2019-09-17 18:16 UTC, jegius approved these changes

2019-09-17 18:24 UTC, jegius approved these changes

2019-09-17 18:24 UTC, merged