Cats max
jegius/java-education-base pull request #23
Opened 2019-09-05 13:33 UTC by MaxKatyshev

Задание с котами. Две семьи

2019-09-14 16:00 UTC, jegius requested changes

2019-09-14 16:00 UTC, jegius commented on src/menu/commands/littletasks/nurserycatsmax/families/Depps.java
> +    private List<Cat> cats;
перенеси эту переменную в верх. Переменные экземпляра должны быть объявлены перед конструктором.

2019-09-14 16:00 UTC, jegius commented on src/menu/commands/littletasks/nurserycatsmax/families/FamilyCat.java
> +
убери лишнюю строку

2019-09-14 16:00 UTC, jegius commented on src/menu/commands/littletasks/nurserycatsmax/CatShelterSingleton.java
> +    private List<Cat> houseOfCats ;
убери пробел лишний и подними переменную над конструктором

2019-09-14 16:00 UTC, jegius commented on src/menu/commands/littletasks/nurserycatsmax/CatGenerator.java
> +            int amountOfCats = (int) Math.floor(Math.random()*5);
`random()*5` потерял пробелы между знаком умножения

2019-09-14 16:00 UTC, jegius commented on src/menu/commands/littletasks/nurserycatsmax/NurseryForCatsMax.java
> +    private static List<FamilyCat> families = new ArrayList<>(Arrays.asList(
Идея хорошая, реализация не очень, убери это поле и в цикле for сразу получай семьи из хранилища семей.
Должно получится как то так:

`for(FamilyCat family : MaxFamilies.getFamilies()){ ... }`

2019-09-14 16:00 UTC, jegius commented on src/menu/commands/littletasks/nurserycatsmax/families/Jacksons.java
> +    private List<Cat> cats;
Тоже самое, объявление переменных должно быть над конструктором

2019-09-15 21:00 UTC, jegius requested changes

2019-09-15 21:00 UTC, jegius commented on src/menu/commands/littletasks/nurserycatsmax/NurseryForCatsMax.java
> +    private static List<FamilyCat> families = new ArrayList<>(Arrays.asList(
Вот это замечание ты похоже просмотрел, все же думаю нужно поправить.

2019-09-16 13:25 UTC, MaxKatyshev commented on src/menu/commands/littletasks/nurserycatsmax/NurseryForCatsMax.java
> +    private static List<FamilyCat> families = new ArrayList<>(Arrays.asList(
Вроде исправил. У меня в коде так сейчас

    public static void run() {
        for (FamilyCat family : MaxFamilies.getFamilies()) {
            family.giveCatsToShelter();
        }

        CatShelterSingleton.getInstance().showAllCats();
    }

2019-09-17 19:22 UTC, jegius approved these changes

2019-09-18 11:32 UTC, merged