Bottle branch
jegius/java-education-base pull request #24
Opened 2019-09-05 15:15 UTC by AlexBossss

2019-09-06 12:46 UTC, MaxKatyshev requested changes

2019-09-06 12:46 UTC, MaxKatyshev commented on src/menu/commands/littletasks/alexninetyninebottles/AlexNinetyNineBottles.java
> +
пробел лишний

2019-09-06 12:46 UTC, MaxKatyshev commented on src/menu/commands/littletasks/alexninetyninebottles/AlexNinetyNineBottles.java
> +
еще один пробел

2019-09-17 10:45 UTC, MaxKatyshev commented
Мои замечания исправлены

2019-09-17 10:50 UTC, MaxKatyshev reviewed
Четко

2019-09-17 11:21 UTC, jegius requested changes

2019-09-17 11:21 UTC, jegius commented on src/menu/commands/littletasks/alexninetyninebottles/readme.md
> +## 99 бутылок пива на столе.
Тоже самое, копировать readme нет смысла

2019-09-17 18:11 UTC, jegius approved these changes

2019-09-17 18:11 UTC, merged