сделал задание с Енамами
jegius/java-education-base pull request #31
Opened 2019-09-22 11:41 UTC by AlexBossss

2019-09-26 19:29 UTC, MaxKatyshev reviewed
Несколько пробелов, остальное всё правильно

2019-09-26 19:29 UTC, MaxKatyshev commented on src/menu/commands/littletasks/simpleenum/Alex/AlexTask.java
> +
Пробел

2019-09-26 19:29 UTC, MaxKatyshev commented on src/menu/commands/littletasks/simpleenum/Alex/AlexTask.java
> +
Пробел

2019-09-26 19:29 UTC, MaxKatyshev commented on src/menu/commands/littletasks/simpleenum/Alex/MusicianType.java
> +
Пробел

2019-10-09 14:09 UTC, MaxKatyshev reviewed
все гуд

2019-10-10 08:58 UTC, jegius requested changes

2019-10-10 08:58 UTC, jegius commented on src/menu/commands/littletasks/simpleenum/Alex/MusicianFactory.java
> +        switch( musicianType) {
лишний пробел перед `musicianType`

2019-10-16 13:59 UTC, jegius approved these changes

2019-10-16 13:59 UTC, merged