18 first stage alex
jegius/java-education-base pull request #34
Opened 2019-09-30 15:49 UTC by AlexBossss

2019-09-30 15:51 UTC, AlexBossss commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +
пробел

2019-09-30 15:51 UTC, AlexBossss commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +
пробел

2019-09-30 15:51 UTC, AlexBossss commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +
пробел

2019-09-30 15:51 UTC, AlexBossss commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +
пробел

2019-10-01 07:12 UTC, MaxKatyshev commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +
петух

2019-10-01 07:12 UTC, MaxKatyshev commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +
карась

2019-10-01 07:13 UTC, MaxKatyshev commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +
бен аффлек

2019-10-01 07:14 UTC, MaxKatyshev commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +
испугался?

2019-10-09 14:01 UTC, MaxKatyshev commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +        size = 0;
Тут не надо разве так this.values, this.size ?

2019-10-09 14:05 UTC, MaxKatyshev commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +        throw new Exception("No realization for this method!");
Почему этот метод пустой?

2019-10-09 14:06 UTC, MaxKatyshev reviewed
проверяй

2019-10-09 18:38 UTC, MaxKatyshev reviewed
Гуд

2019-10-10 07:08 UTC, jegius requested changes

2019-10-10 07:08 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +        throw new Exception("No realization for this method!");
он будет реализован на другом этапе

2019-10-10 07:08 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +            values = new long[values.length + 16];
убери магическое число, сделай enum с константами и заюзай их тут

2019-10-10 07:08 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +            System.arraycopy(temp, 0, values, 0, temp.length);
тоже самое, абсолюно не понятно что за 0

2019-10-10 07:08 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +            values[size - 1] = 0;
какой то костыль, лучше сделай в цикле проверку на наличие в массиве элемента `values[index + 1]`

2019-10-10 07:08 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +        values = new long[16];
вынеси 16 в константы с понятным названием

2019-10-10 07:08 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +        this.values = new long[16];
Тоже самое, выведи 16 в енам с константами с понятным названием

2019-10-10 07:08 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +            values[size] = data;
`values[size] = data;` повторяется и в `if` и в `else`, это значит что можно убрать его из условия `if`, убрать его из `else` и оставить в теле метода, как это сделано с `size++`

2019-10-10 07:08 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +        return isFound ? foundIndex : -1;
-1 тоже вынеси в константы

2019-10-16 13:56 UTC, jegius requested changes

2019-10-16 13:56 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +            values[size] = data;
тут так и не вижу изменений

2019-10-16 13:56 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +        return isFound ? foundIndex : -1;
тоже не вижу

2019-10-16 13:56 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/NumbersForAlexArray.java
> +
лишние пробелы

2019-10-16 15:02 UTC, jegius requested changes

2019-10-16 15:02 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +        } else {
зачем пустой блок else?

2019-10-18 09:08 UTC, jegius approved these changes

2019-10-18 09:08 UTC, merged