19 finished second stage alex
jegius/java-education-base pull request #40
Opened 2019-10-24 14:24 UTC by AlexBossss

2019-10-30 06:41 UTC, MaxKatyshev commented on src/App.java
> +        }
Вася, шо это тут делает? Таки нельзя так делать, дорогой мой

2019-10-30 06:41 UTC, MaxKatyshev commented on src/menu/commands/tasks/collections/iterator/AlexIterator.java
> +
пробел

2019-11-07 12:06 UTC, jegius requested changes

2019-11-07 12:06 UTC, jegius commented on src/menu/commands/tasks/collections/arraylist/AlexArrayList.java
> +public class AlexArrayList implements List{
что с пробелом?

2019-11-07 12:06 UTC, jegius commented on src/menu/commands/tasks/collections/iterator/AlexIterator.java
> +        if(list.size() !=0) {
где пробелы потерял?

2019-11-07 12:06 UTC, jegius commented on src/menu/commands/tasks/collections/iterator/AlexIterator.java
> +            return -1;
Магические номера вынеси в константы

2019-11-07 12:06 UTC, jegius commented on src/menu/commands/tasks/collections/iterator/AlexIterator.java
> +        if (list.size() != 0)
Тоже самое

2019-11-07 12:06 UTC, jegius commented on src/menu/commands/tasks/collections/iterator/AlexIterator.java
> +        this.index = 0;
Тоже самое

2019-11-10 15:11 UTC, jegius requested changes

2019-11-10 15:11 UTC, jegius commented on src/menu/commands/tasks/collections/iterator/AlexIterator.java
> +        if (list.size() != INITIAL_SIZE_OF_LIST.getValue())
Скобки фигурные забыл

2019-11-10 15:11 UTC, jegius commented on src/menu/commands/tasks/collections/iterator/AlexIterator.java
> +            list.remove(index - 1);
почему мы удаляем предидущий?

2019-11-12 11:19 UTC, jegius approved these changes

2019-11-12 11:19 UTC, merged