переделываю реадктор
jegius/java-education-base pull request #60
Opened 2020-01-11 18:57 UTC by AlexBossss

2020-01-11 19:19 UTC, jegius requested changes

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +    private static final String fileNameExample = "\\w+\\.txt";
1) если это константа то все с снейк кейсе в upperCase `FILE_NAME_EXAMPLE`
2) название переменной врет, это не пример имени файла, это скорее проверка его на валидность. Дай переменной правильное имя

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +public class AlexEditorFileMenu {
Это не `EditoFileMenu` это скорее сервис по работе с файлами.

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +    private List<String> lines;
зачем тебе lines? Считанные строчки должны храниться в объекте который будет работать с файлами

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +    private Path file;
Зачем тебе всегда хранить путь? Путь нужен только один раз, чтобы открыть файл. Дальше этот сервис ничего про путь знать не должен

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +    private int fileNumber =  0;
зачем это?

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +            usedFiles = new ArrayList<>();
если пользователь который раньше открывал файл решит открыть новый файл то все ранее открытые файла удалятся?

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +            usedFiles = new ArrayList<>();
Вообще логика работы с ранее открытыми файлами должна быть делегирована сервису работы с файлами

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +            System.out.println("Only txt files available");
может быть пользователю нужно сразу дать возможность повторно попробовать ввести новый путь?

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +    private List <String> usedFiles;
это нужно перенести в отдельный сервис и уже его использовать тут

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +            for(String fileName: usedFiles){
тут должен быть вызов метода из сервиса работы с путями типа `pathService.showAvailablePaths()` который возвращает `Path` который потом передаст в getFile

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +    private void getFile(String fileName){
тут вообще не понятно, почему бы сразу не принимать путь?

2020-01-11 19:19 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorFileMenu.java
> +    private void getFile(String fileName){
Этот метод должен создавать новый объект редактора который будет работать с файлом передавать в него путь и  вызывать у него метод типа `run` или `execute` - который передаст ему управление и даст возможности типа сохранения, редактирования и т.п.

2020-01-22 21:07 UTC, jegius requested changes

2020-01-22 21:07 UTC, jegius commented on alex2.txt
> +hi alex
зачем коммитить эти файлы?

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +            if (filePath == null) {
а почему бы этот эксепшен не кидать в paths?

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +            int choice = scanner.nextInt();
что будет если пользователь введет текст?

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +                    selectChoice();
где braek? ко всем case относится

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +            System.out.println("only numbers");
как то странно это выглядит, если пользователь вводи не то что ты хочешь ты сразу вылетаешь из меню. Сделай валидацию до токо как зайдешь в свитч кейс

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +        Scanner scanner = new Scanner(System.in);
думлайю не самая лучшая идея создавать новый сканнер на каждый чих. Когда эдитор создается сохрани сразу сканер в переменные экземпляра и юзай его везде.

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +                System.out.print(lineNumber++ + ": ");
сделай это поаккуратнее, например создай специальную функцию в menuUtils которая будет принимать lineNumber и line и красиво это печатать

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +            out.close();
почитай про autoclosable и try с ресурсами, и заюзай это тут

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +            e.printStackTrace();
сделай адекваютю ошибку которая будет понятна неквалифицированному пользователю.

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +        AlexEditorPaths.getInstance().addFile(filePath.toString());
добавлять файл лучше в AlexEditorPaths до того как path передается в editor

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +        Path filePath = Paths.get(fileName);
тут же и сохраняй патх в массив путей

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +            fileName = scanner.nextLine();
если ты собираешься гонять тут бесконечно человека который вводит невалидное имя файла, то хотябы сообщи ему об этом. Можешь к примеру в Paths.get проверять эксепшен который падает если файл не найден и просить ввести заново

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/SelectFileService.java
> +        filePath = AlexEditorPaths.getInstance().selectFile();
Зачем создавать объект AlexEditor с null когда ты уже знаешь что файлов нет? проверь здесь. По хорошему все таки null замени на Excaption и обработай его тут с понятным сообщением и выведи меню где пользователь выбирает из нового и уже использованных ранее путей.

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/SelectFileService.java
> +    public AlexEditor getNewFile() { filePath =  AlexEditorPaths.getInstance().newFile();
почему на одной строчке filePaht с именем метода?

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +                Scanner scanner = new Scanner(System.in);
тоже самое что и с Editor. При создании экземпляра создай сканнер в объектке и везде его переюзай

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +                System.out.println((fileNumber++) + " : " + file);
Тоже что и со строчками в файлах, следай удобный метод в MenuUtils

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +                while (choice > files.size() || choice < 1) {
мне кажется намного правильнее будет попытаться взять файл в paths.get и если файла нет, сообщить об этом пользователю и вывести меню заново. Очень плохо привязываться к не связанным напрямую с твоей целью вещам типа размера массива. Цель все таки получить валидный пут и првильно тут все обработать

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +            } catch (InputMismatchException e) {
ой блин, а это что такое? Запомни, никогда нельзя использовать пустые cactch блоки. Если есть catch блок - он обязан писать тебе что за ошибка упала. За это тебе могут и руки поламать если не дай боже ты на реальном проекте так напишишь.

2020-01-22 21:07 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorCommand.java
> +            System.out.println("Only numbers");
сделай валидацию до того как войдешь в switch

2020-01-27 18:19 UTC, AlexBossss commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +                while (choice > files.size() || choice < 1) {
Ты имеешь ввиду сделать отдельный метод getPath который будет доставать пас и массива?

2020-02-06 21:38 UTC, jegius requested changes

2020-02-06 21:38 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +            e.printStackTrace();
тут не поправил

2020-02-06 21:38 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorCommand.java
> +            System.out.println("Only numbers");
Тоже не исправил

2020-02-06 21:38 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +        addFile(fileName);
Сохраняй Path в массиве, мы уже это обсуждали.

2020-02-06 21:38 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +            Scanner scanner = new Scanner(System.in);
сохрани сканер в переменных экземпляра и используй его тут, не нужно создавать по сканеру на каждый чих.

2020-02-06 21:38 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +        addFile(fileName);
проверь что будет если в названии файла будут пробелы в начале пути и в его конце? если из-за этого путь ломается сделай .trim()

2020-02-06 21:38 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +            System.out.println("Enter file name");
![image](https://user-images.githubusercontent.com/11362702/73980140-101d0900-4949-11ea-82a4-cc20cc979b76.png)

И как понять что тут не так? Если есть ошибка, напиши что именно тебя не устраивает

2020-02-06 21:38 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +        System.out.println("Lines in the " + filePath.toString() + ": " + lines.size());
![image](https://user-images.githubusercontent.com/11362702/73980266-53777780-4949-11ea-941d-c2673d15bc4d.png)

а где редактирование строки по номеру?

2020-02-06 21:38 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +        MenuUtils.printOption("4", "Save");
![image](https://user-images.githubusercontent.com/11362702/73980332-72760980-4949-11ea-8d59-90b1d9e747a6.png)

Сделай так чтобы по умолчанию (если путь не задан абсолютный) файл создавался не в корне а в директории out

2020-02-06 21:38 UTC, jegius commented on src/menu/utils/MenuUtils.java
> +        }catch(InputMismatchException e){
пробелы в catch

2020-02-06 21:38 UTC, jegius commented on src/menu/utils/MenuUtils.java
> +        }catch(InputMismatchException e){
почему не использовал этот метод только в одном месте где был выбор?

2020-02-09 08:20 UTC, jegius requested changes

2020-02-09 08:20 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditor.java
> +                selectChoice();
почему тут нет break?

2020-02-09 08:20 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +        if (fileName.contains("/Users")){
/Users вынеси в константу

2020-02-09 08:20 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +            scanner = new Scanner(System.in);
здесь  нельзя использовать MenuUtils.getScannerChoice()?

2020-02-11 19:12 UTC, jegius approved these changes

2020-02-11 19:12 UTC, jegius commented on src/menu/commands/tasks/editor/alex/AlexEditorPaths.java
> +    private static final String DEFAULT_PATH = "/Users/alexperminov/IdeaProjects/java-education-base/out/";
не исправляй но такой путь не правильный. Никогда нельзя делать переменную которя знает конкретные пути. Путь должен быть относительным и не должен зависить ни от системы ни от проекта ни уж тем более от имени пользователя

2020-02-11 19:12 UTC, merged