58-generic-max
jegius/java-education-base pull request #61
Opened 2020-02-17 10:59 UTC by MaxKatyshev

2020-02-17 22:22 UTC, jegius requested changes

2020-02-17 22:22 UTC, jegius commented on src/menu/commands/tasks/TaskMenuCommand.java
> -        MenuUtils.printOption("6", "Show Alex Editor");
так, зачем ты удалил Лехин editor?

2020-02-17 22:22 UTC, jegius commented on src/menu/commands/tasks/TaskMenuCommand.java
> -                return AlexEditorCommand.getInstance().execute();
Никогда не удаляй чужой код без спроса

2020-02-17 22:22 UTC, jegius commented on src/menu/commands/tasks/generics/max/GeneratorMonster.java
> +}
добавь пустую строчку в конце

2020-02-17 22:22 UTC, jegius commented on src/menu/commands/tasks/generics/max/EnumForMonsters.java
> +}
добавь пустую строчку в конце

2020-02-17 22:22 UTC, jegius commented on src/menu/commands/tasks/generics/max/ExceptionsOutOfArrSizeGeneric.java
> +}
добавь пустую строчку в конце

2020-02-17 22:22 UTC, jegius commented on src/menu/commands/tasks/generics/max/MaxArrayListGeneric.java
> +        Object[] temp = values;
у тебя тут копирование будет происходить всегда, и когда надо и когда ненадо, это очень трудозатратно. Сделай так, чтобы массив имел буфер (например 16) и расширялся только по достижению этого лимита

2020-02-18 09:43 UTC, MaxKatyshev commented on src/menu/commands/tasks/TaskMenuCommand.java
> -                return AlexEditorCommand.getInstance().execute();
я сделал так, чтобы его едитор был. все проверил перед пуллом. видимо опять не так все в идее понял
исправлю

2020-02-20 08:24 UTC, jegius approved these changes

2020-02-20 11:46 UTC, merged