57 editor max
jegius/java-education-base pull request #68
Opened 2020-03-09 12:14 UTC by MaxKatyshev

сделал едитор

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxEditor.java
> +            System.out.println(e.getMessage());
почему бы тут не вызвать опять этот медот? сейчас он кидает выше на уровень, не очень удобно

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxEditor.java
> +        try {
нет ни close ни аргумента try, сделай аргумент в трай с автоклозабле

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +    private String enterFileName() {
название как по мне не очень, метод чтоле вводит имя или что

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +        while (!fileName.matches(FILE_EXTENSION)) {
раз уж сделал отдельный метод с приемом имени файла, то и проверку туда лучше

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +    private Path fileMatch(String pathToFile) {
название метода и то что он делает не совпадает

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +    private void validateFile(Path path) {
тоже самое с названием метода. проверок нет, думаю валидейт сюда не подойдет

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +    private void createFile(Path providedPath, String providedFileName) {
А зачем тут стринг файл нейм? не понял я для чего она тебе тут? чтобы избежать ".out/"?

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +        if (pathToFile.isEmpty()) {
если добавить проверку в метод как я написал выше, то данная проверка не понадобиться

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxEditor.java
> +                    .openFile()
почему ты тут кидаешь опен файл?
попробуй такой кейс: 
-создай файл
-удали его
-пропробуй открыть
он тебе кидает всегда опен файл, а у тебя нет файлов никаких, выйти от сюда не получится

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxEditor.java
> +        Scanner scanner = new Scanner(System.in);
для такого случая есть метод в утилитах

2020-03-17 05:44 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/exceptions/NoSuchSelectException.java
> +        super("No such select");
звучит не очень)

2020-03-17 13:21 UTC, MaxKatyshev commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +    private void createFile(Path providedPath, String providedFileName) {
чтобы по красоте выводилось
"File q.txt is created"
А не так 
"File ./out/q.txt is created"

2020-03-17 13:34 UTC, MaxKatyshev commented on src/menu/commands/tasks/editor/max/exceptions/NoSuchSelectException.java
> +        super("No such select");
вот ты воздухан( везде доебался(((

2020-04-06 18:14 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxSerializableManagerXML.java
> +
пробел)

2020-04-06 18:14 UTC, AlexBossss commented on src/menu/commands/tasks/editor/max/MaxSerializableManagerJava.java
> +    public MaxSerializableManagerJava() {
разве нужен тут конструктор пустой?

2020-04-07 14:54 UTC, jegius commented
![image](https://user-images.githubusercontent.com/11362702/78684131-2a4f7500-7901-11ea-99dc-17734834320d.png)

Почему при создании файла система пишет мне file doesn't exist! если я еще ничего не вводил?

2020-04-07 14:57 UTC, jegius commented
![image](https://user-images.githubusercontent.com/11362702/78684421-7ac6d280-7901-11ea-825d-0409c38e921d.png)

А если я нажал на этот пункт по ошибке, или если тут нет нужно мне файла, мне все равно придется что-то открыть? Сделай пункт back.

2020-04-07 14:58 UTC, jegius commented
![Uploading image.png…]()

Открытие файла не работает.

2020-04-07 15:02 UTC, jegius commented
![image](https://user-images.githubusercontent.com/11362702/78684739-e4df7780-7901-11ea-9b58-d41918ba2d08.png)

поправь текст сообщения. С ходу я бы подумал что ты предлагаешь перезаписать этот файл. Напиши что-нибудь в стиле, "файл с таким именем Уже существует, вы можете открыть существующий файл или создать файл с другим именем" -открыть существующий файл - создать файл с другим именем

2020-04-07 15:04 UTC, jegius commented
![image](https://user-images.githubusercontent.com/11362702/78685215-7e0e8e00-7902-11ea-8882-eabff754847d.png)

если файл удалить и он не будет открываться, то в списке ранее открытых файлов он все равно останется

2020-04-07 15:05 UTC, jegius requested changes

2020-04-07 15:05 UTC, jegius commented on src/menu/commands/tasks/editor/max/MaxEditor.java
> +            for (String line : lines) {
зачем эта манипуляция? почему нельзя взять ввод пользователя -1, выполнить .get(ввод пользователя) и просто его не поменять?

2020-04-07 15:05 UTC, jegius commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +            choice = MenuUtils.getScannerChoice();;
двойная точка с запятой

2020-04-07 15:05 UTC, jegius commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +            for (String file : allFiles) {
Цикл вынеси в отдельный метод вместе с Select file, сделай это как нибудь универсально, чтобы можно было любой текст прокинуть в метод и вывести его как заголовок

2020-04-07 15:05 UTC, jegius commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +        System.out.println("Enter file name:");
Работу со сканером тоже лучше вынеси в отдельный метод с generic, чтобы можно было получать любые нужные тебе данные и прокидывать в этот метод заоловок

2020-04-07 15:05 UTC, jegius commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +    private List<String> allFiles;
Эта переменная не используется нигде кроме метода selectPreviousFile. Сделай ее локальной для этого метода

2020-04-07 15:05 UTC, jegius commented on src/menu/commands/tasks/editor/max/MaxEditorManager.java
> +        if (Files.exists(path)) {
перепиши через `? :` + не очень понятна логика который ты хотел добиться, после выполнения обоих методов все равно создастся new MaxEditor с неправильным путем.

2020-04-21 00:43 UTC, jegius requested changes

2020-04-21 00:43 UTC, jegius commented on src/menu/commands/tasks/editor/max/MaxEditor.java
> +    public static synchronized MaxEditor getInstance() {
Так, почему MaxEditor - Синглтон? и у него в полях хранятся данные и не чистятся? Его нужно сделать простым объектом. Убери все код синглтона из кода

2020-04-21 00:43 UTC, jegius commented on src/menu/commands/tasks/editor/max/MaxEditor.java
> +    private MaxEditor() {
Тоже бесполезные строки, убиери приватный конструктор

2020-05-02 16:58 UTC, jegius approved these changes

2020-05-02 16:58 UTC, merged